server:
  port: 8080

spring:
  application:
    name: spring-ai-workflow
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
