server:
  port: 8080
spring:
  application:
    name: spring-ai-workflow-orchestrator
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
        completions-path: /v1/chat/completions