services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos-standalone-derby
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN=${your_nacos_auth_secret_token}
      - NACOS_AUTH_IDENTITY_KEY=${your_nacos_server_identity_key}
      - NACOS_AUTH_IDENTITY_VALUE=${your_nacos_server_identity_value}
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"